# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b467efcaf53f75c05ebe25fd30c701b7ceb9a4ec2d57320ab7e73874fdeb58de8991d16ccddd20e792526e4895ad1b4817301e964ba7916853908ab82d6b2bd5

test:
  secret_key_base: dc936d3cfbea0749003c09c4e3a75f4326d4adc870580fd3b664062ec336db2d83025710f565aa8ec5c81068f50f4073e5444b10c0880a6cb3d11ccbb083e870

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
